---
layout: cv
title: Kimberly Juarez's CV
---
# Kimberly Juarez
Student.

<div id="webaddress">
<a href="jua22004@byui.edu">My email</a>
| <a href="https://kimy2905.github.io/Portafolio-Kimberly-Juarez/">My personal portafolio</a>
</div>


## Currently

Majoring in Data Science 

### Specialized in

Data Analytics with a minor in Software Engineering


### Research interests

- Data Mining and Knowledge Discovery
- Big Data Analytics
- Machine Learning and Predictive Analytics
- Data Visualization


## Education

`2012-2021`
__Colegio Santa Teresita__

`2022 - Now`
__Brigham Young University-Idaho__


## Awards

`2024`
President, *Society of Women Engineers*, Rexburg, Idaho

President, *BYUI-Hack*, Rexburg, Idaho

## Languages
`Spanish`
__Fluent__

`English`
__Fluent__

### Porjects

`October 2024`
Bussiness Website 

`January 2025`
ASL translator

### Linkedin
Let's chat, (www.linkedin.com/in/kimberly-juarez-palomino) 


## Occupation

` April 2024`
___, Support Center

- Customer Service

`September 2024 - Present`
__Teacher Assistant__, Brigham Young University-Idaho

- HTML/CSS



<!-- ### Footer

Last updated: May 2013 -->